apiVersion: v1
kind: Namespace
metadata:
  name: kube-migrator
---
apiVersion: v1
kind: Service
metadata:
  name: kube-migrator-mysqldb-service
  namespace: kube-migrator
spec:
  selector:
    app: kube-migrator-mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-migrator-mysqldb
  namespace: kube-migrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-migrator-mysqldb
  template:
    metadata:
      labels:
        app: kube-migrator-mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypass1234
            - name: MYSQL_DATABASE
              value: kubemigrator
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kube-migrator-backend-service
  namespace: kube-migrator
spec:
  type: LoadBalancer
  selector:
    app: kube-migrator-backend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-migrator-backend
  namespace: kube-migrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-migrator-backend
  template:
    metadata:
      labels:
        app: kube-migrator-backend
    spec:
      containers:
        - name: backend
          image: baha00/kube-migrator:backend-latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://kube-migrator-mysqldb-service:3306/kubemigrator?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: mypass1234
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_APPLICATION_NAME
              value: Kube-Migrator
            - name: SERVER_PORT
              value: "8090"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-migrator-frontend-service
  namespace: kube-migrator
spec:
  type: LoadBalancer
  selector:
    app: kube-migrator-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-migrator-frontend
  namespace: kube-migrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-migrator-frontend
  template:
    metadata:
      labels:
        app: kube-migrator-frontend
    spec:
      containers:
        - name: frontend
          image: baha00/kube-migrator:frontend-latest

